# https://taskfile.dev

version: "3"

vars:
  terraform_version: 1.11.3
  vault_version: 1.18.5
  packer_version: 1.12.0
  nomad_version: 1.9.7
  nomadpack_version: 0.2.0
  consul_version: 1.20.5
  waypoint_version: 0.11.4
  boundary_version: 0.19.1
  change_shell: true

run: once

set:
  - errexit
  - nounset
  - pipefail

includes:
  deps:
    taskfile: .Taskfile.dependencies.yml
    internal: true
  config:
    taskfile: .Taskfile.configure.yml
    internal: true

tasks:
  default:
    desc: Setup workstation configuration
    aliases:
      - setup
    cmds:
      - task: sudo
      - task: gcc
      - task: shell
      - task: tmux
      - task: neovim
      - task: deps:ghq
      - task: hashi

  fix-git-status:
    desc: Fixes the `git status` in the dotfiles directory
    cmds:
      - cmd: git update-index --assume-unchanged configs/nvim/lazy-lock.json

  nerdfonts:hack:
    run: once
    desc: Install Hack (Nerd Font) for nicer characters in shell
    cmds:
      - cmd: sudo mkdir -p /usr/local/share/fonts/NerdFonts
        silent: true
      - cmd: sudo curl -fLo /usr/local/share/fonts/NerdFonts/HackNerdFontMono-Regular.ttf https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/Hack/Regular/HackNerdFontMono-Regular.ttf
      - cmd: sudo curl -fLo /usr/local/share/fonts/NerdFonts/HackNerdFontMono-Bold.ttf https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/Hack/Bold/HackNerdFontMono-Bold.ttf
      - cmd: sudo curl -fLo /usr/local/share/fonts/NerdFonts/HackNerdFontMono-Italic.ttf https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/Hack/Italic/HackNerdFontMono-Italic.ttf
      - cmd: sudo curl -fLo /usr/local/share/fonts/NerdFonts/HackNerdFontMono-BoldItalic.ttf https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/Hack/BoldItalic/HackNerdFontMono-BoldItalic.ttf
      - cmd: |
          if command -v fc-cache &>/dev/null; then
            fc-cache -v /usr/local/share/fonts/NerdFonts
          fi
        silent: true
    method: timestamp
    interactive: true
    status:
      - test -e /usr/local/share/fonts/NerdFonts/HackNerdFontMono-Regular.ttf
      - test -e /usr/local/share/fonts/NerdFonts/HackNerdFontMono-Bold.ttf
      - test -e /usr/local/share/fonts/NerdFonts/HackNerdFontMono-Italic.ttf
      - test -e /usr/local/share/fonts/NerdFonts/HackNerdFontMono-BoldItalic.ttf

  ghostty:
    desc: Install Ghostty terminal emulator
    run: once
    cmds:
      - task: ghostty:dep
      - task: ghostty:config

  ghostty:dep:
    run: once
    interactive: true
    deps:
      - sudo
    cmds:
      - cmd: sudo snap install ghostty --classic
    status:
      - test -x /snap/bin/ghostty

  ghostty:config:
    run: once
    deps:
      - deps:zsh
      - nerdfonts:hack
    cmds:
      - cmd: mkdir -p ~/.config/ghostty
        silent: true
      - cmd: install -b '{{ .TASKFILE_DIR }}/configs/ghostty/config' ~/.config/ghostty/config
    status:
      - test -e ~/.config/ghostty/config
      - grep -qe '^command = ""' -e '^command = ".*/zsh.*"' ~/.config/ghostty/config
      - grep -qe '^font-family = ""' -e '^font-family = "Hack Nerd Font Mono"' ~/.config/ghostty/config
      - grep -qe '^theme = ""' -e '^theme = "gruvbox.*"' ~/.config/ghostty/config

  hashi:
    internal: true
    desc: Install the HashiCorp suite of software
    run: once
    cmds:
      - task: deps:terraform
      - task: deps:vault
      - task: deps:packer
      - task: deps:nomad
      - task: deps:nomad:pack
      - task: deps:consul
      - task: deps:waypoint
      - task: deps:boundary

  sudo:
    internal: true
    desc: Setup passwordless sudo for current user
    run: once
    interactive: true
    cmds:
      - cmd: printf '%s\tALL=(ALL:ALL) NOPASSWD:ALL\n' "$(whoami)" | sudo tee /etc/sudoers.d/99-local-changes >/dev/null
    status:
      - sudo test -e /etc/sudoers.d/99-local-changes

  gcc:
    internal: true
    desc: Install a C compiler of some sort
    run: once
    preconditions:
      - sh: command -v apt &>/dev/null
        msg: "requires `apt` to be installed"
      - sh: command -v sudo &>/dev/null
        msg: "requires `sudo` to be installed"
    cmds:
      - cmd: |
          sudo apt update -y
          sudo apt install -y build-essential
    status:
      - command -v gcc &>/dev/null
      - command -v make &>/dev/null

  neovim:
    internal: true
    desc: Install and configure NeoVim as an editor
    deps:
      - nerdfonts:hack
    cmds:
      - task: deps:neovim
      - task: deps:neovim:shim
      - task: deps:neovim:lsp
      - task: config:neovim
    silent: true

  tmux:
    internal: true
    desc: Install and configure tmux as a terminal multiplexer
    deps:
      - nerdfonts:hack
    cmds:
      - task: deps:tmux
      - task: config:tmux
    silent: true

  shell:
    internal: true
    desc: Configure the shell environment for ZSH
    deps:
      - nerdfonts:hack
    cmds:
      - task: config:xdg
      - task: deps:git
      - task: config:git
      - task: deps:nix
      - task: deps:zsh
      - task: deps:zplug
      - task: deps:starship
      - task: config:starship
      - task: deps:fzf
      - task: deps:direnv
      - task: config:zsh
      - cmd: |
          if [ -e ~/.bashrc ]; then
            if ! grep -qFe '.local/bin' ~/.bashrc &>/dev/null; then
              printf '\nexport PATH="${HOME}/.local/bin:${PATH}"\n' >> ~/.bashrc
            fi
          elif [ -e ~/.bash_profile ]; then
            if ! grep -qFe '.local/bin' ~/.bash_profile &>/dev/null; then
              printf '\nexport PATH="${HOME}/.local/bin:${PATH}"\n' >> ~/.bash_profile
            fi
          fi
        silent: true
