# https://taskfile.dev

version: "3"

vars:
  terraform_version: 1.11.3
  vault_version: 1.18.5
  change_shell: true

run: once

set:
  - errexit
  - nounset
  - pipefail

includes:
  deps:
    taskfile: .Taskfile.dependencies.yml
    internal: true
  config:
    taskfile: .Taskfile.configure.yml
    internal: true

tasks:
  setup:
    aliases:
      - default
    cmds:
      - task: gcc
      - task: shell
      - task: tmux
      - task: neovim
      - task: deps:ghq
      - task: deps:terraform
      - task: deps:vault

  gcc:
    run: once
    preconditions:
      - sh: command -v apt &>/dev/null
        msg: "requires `apt` to be installed"
      - sh: command -v sudo &>/dev/null
        msg: "requires `sudo` to be installed"
    cmds:
      - cmd: |
          sudo apt update -y
          sudo apt install -y build-essential
    status:
      - command -v gcc &>/dev/null
      - command -v make &>/dev/null

  neovim:
    cmds:
      - task: deps:neovim
      - task: config:neovim
    silent: true

  tmux:
    cmds:
      - task: deps:tmux
      - task: config:tmux
    silent: true

  shell:
    cmds:
      - task: config:xdg
      - task: deps:git
      - task: config:git
      - task: deps:nix
      - task: deps:zsh
      - task: deps:zplug
      - task: deps:starship
      - task: config:starship
      - task: deps:fzf
      - task: deps:direnv
      - task: config:zsh
    # TODO: Set shell to be zsh
